is_heart: true
is_router: true
is_pacemaker: true

cluster_hostname: local.paasmaker.net
frontend_domain_postfix: ":42530"

master_node: localhost
master_port: 42500

shutdown_daemons_on_exit: true

install_init_script: false
enable_init_script: false
init_redirect_port80: false

runtime_php_enable: true
runtime_php_disable_system_apache: true

runtime_rbenv_enable: false
runtime_rbenv_versions: ['1.9.3-p327']
runtime_rbenv_for_user: false

service_managedmysql_enable: true
service_managedmysql_disable_system_mysql: false

service_managedpostgres_enable: true
service_managedmysql_disable_system_postgres: false

service_managedmongodb_enable: true
service_managedmongodb_disable_system_mongodb: false

service_managedredis_enable: true

write_paasmaker_configuration: true

extra_plugins:
  # CAUTION: Do NOT have this plugin enabled on a production system.
  - name: paasmaker.misc.devdatabase
    title: Development Database Bootstrap plugin
    class: paasmaker.pacemaker.miscplugins.devdatabase.DevDatabasePlugin

  - name: paasmaker.scm.zip
    class: paasmaker.pacemaker.scm.zip.ZipSCM
    title: Zip file SCM
  - name: paasmaker.scm.tarball
    class: paasmaker.pacemaker.scm.tarball.TarballSCM
    title: Tarball SCM
  - name: paasmaker.scm.git
    class: paasmaker.pacemaker.scm.git.GitSCM
    title: Git SCM

  - name: paasmaker.service.parameters
    class: paasmaker.pacemaker.service.parameters.ParametersService
    title: Parameters Service

  - class: paasmaker.pacemaker.scm.devdirectory.DevDirectorySCM
    name: paasmaker.scm.devdirectory
    title: Development Local Directory SCM

  - class: paasmaker.pacemaker.prepare.pythonpip.PythonPipPrepare
    name: paasmaker.prepare.pythonpip
    title: Python PIP preparer